version: "3"
services:
  fio-oracle:
    image: "eostribe/fio_oracle:${TAG}"
    container_name: fio-oracle
    volumes:
      - "/opt/fio.oracle/logs/:/app/controller/api/logs"
    environment:
      - MODE=${MODE}
      - SERVER_URL_HISTORY=${SERVER_URL_HISTORY}
      - SERVER_URL_ACTION=${SERVER_URL_ACTION}
      - POLLTIME=${POLLTIME}
      - POLLOFFSET=${POLLOFFSET}
      - TGASLIMIT=${TGASLIMIT}
      - TGASPRICE=${TGASPRICE}
      - PGASLIMIT=${PGASLIMIT}
      - PGASPRICE=${PGASPRICE}
      - ETHAPIURL=${ETHAPIURL}
      - USEGASAPI=${USEGASAPI}
      - GASPRICELEVEL=${GASPRICELEVEL}
      - FIO_ORACLE_PRIVATE_KEY=${FIO_ORACLE_PRIVATE_KEY}
      - FIO_ORACLE_PUBLIC_KEY=${FIO_ORACLE_PUBLIC_KEY}
      - FIO_ORACLE_ACCOUNT=${FIO_ORACLE_ACCOUNT}
      - ETH_ORACLE_PUBLIC=${ETH_ORACLE_PUBLIC}
      - ETH_ORACLE_PRIVATE=${ETH_ORACLE_PRIVATE}
      - FIO_ORACLE_ADDRESS=${FIO_ORACLE_ADDRESS}
      - FIO_ORACLE_WRAP_ACCOUNT=${FIO_ORACLE_WRAP_ACCOUNT}
      - POLYAPIURL=${POLYAPIURL}